### ISSUE TITLE
eyebrows don't work

### ISSUE THREAD

**Issue by hr1juldey** [Upliner/CharMorph#10]
Python: Traceback (most recent call last):
  File "/home/hrijul279/.var/app/org.blender.Blender/config/blender/3.1/scripts/addons/CharMorph/hair.py", line 206, in execute
    has_fit = fit_all_hair(obj)
  File "/home/hrijul279/.var/app/org.blender.Blender/config/blender/3.1/scripts/addons/CharMorph/hair.py", line 156, in fit_all_hair
    has_fit |= fitter.fit_obj_hair(char)
  File "/home/hrijul279/.var/app/org.blender.Blender/config/blender/3.1/scripts/addons/CharMorph/lib/fitting.py", line 375, in fit_obj_hair
    has_fit |= self.fit_hair(obj, i)
  File "/home/hrijul279/.var/app/org.blender.Blender/config/blender/3.1/scripts/addons/CharMorph/lib/fitting.py", line 350, in fit_hair
    cnts, data, binding = self.get_hair_data(psys)
TypeError: cannot unpack non-iterable NoneType object

location: <unknown location>:-1

eyebrow addition makes this error

**Comment by Upliner** [comment]
Fixed in 0.3.1-beta4
