### ISSUE TITLE
Crash: Reom + Character+Assets setting

### ISSUE THREAD

**Issue by GeneralProtectionFault** [Upliner/CharMorph#35]
Gonna just use Blender's issue report template =)

**System Information**
Operating system: Linux-6.10.5-zen1-1-zen-x86_64-with-glibc2.40 64 Bits, X11 UI
Graphics card: NVIDIA GeForce RTX 3060/PCIe/SSE2 NVIDIA Corporation 4.6.0 NVIDIA 555.58.02

**Blender Version**
Broken: version: 4.2.0, branch: blender-v4.2-release, commit date: 2024-07-16 06:20, hash: `a51f293548ad`
Worked: N/A

**Short description of error**
Blender crashes when trying to finalize the Reom character if you select Character+Assets.  Here is the error:
`Traceback (most recent call last):
File "/home/user/.config/blender/4.2/scripts/addons/CharMorph/common.py", line 190, in execute
return self.exec(context, context.window_manager.charmorph_ui)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/user/.config/blender/4.2/scripts/addons/CharMorph/finalize.py", line 272, in exec
_import_expresions(ui.fin_expressions == "CA")
File "/home/user/.config/blender/4.2/scripts/addons/CharMorph/finalize.py", line 237, in _import_expresions
fitted_data = afd.binding.fit(data)
^^^^
NameError: name 'data' is not defined`

**Exact steps for others to reproduce the error**
* Select Reom as the character
* Import Character
* Expand Finalization tab and select "Character+Assets" under the Expressions dropdown
* Click Finalize

**Comment by Hopefullyidontgetbanned** [comment]
on latest commit on windows 11, It does not crash, it simply gives the same error but remains stable.

**Comment by GeneralProtectionFault** [comment]
My system info is up there, it's not Windows 11 (thank God LOL). However, it doesn't actually crash Blender entirely for me either, but it's an unhandled exception.  The only reason Blender stays up is because it just "catches" the addon's crash.  

I assume what is needed there is for the addon to catch it.  I don't know what's going on in there, only started peeking at it, but if it's just that such-and-such a figure doesn't have assets, then simply handling that in the code so it displays some message to indicate that we can't do that yet, or just says "there are no assets for ____" or something.  

The issue is here in finalize.py:
`        if add_assets:
            for afd in fitter.get_assets():
                fitted_data = afd.binding.fit(**data**)
                if ((fitted_data ** 2).sum(1) < 1e-6).all():
                    continue
                fitted_data += afd.geom.verts
                sk = get_exp_sk(afd.obj, name)
                sk.data.foreach_set("co", fitted_data.reshape(-1))
`

Point being, there's a mistake in the code there.  I took a look and I don't see that "data" variable anywhere in the entire finalize.py file.  Should it be obj.data?  Anyhoo, that code doesn't run if I do the same with Antonia, for example.  Hard to tell just at a quick glance, but I guess that character does not have expression morphs and it never iterates over them.  Again, just guessing if it helps any.

**Comment by Hopefullyidontgetbanned** [comment]
Well it's the same behaviour in Windows and Linux so that's a relief at least. I believe it's because charmorph doesn't import reom's L3 morphs by default but I could be wrong.
