### ISSUE TITLE
Importing character & get error

### ISSUE THREAD

**Issue by shubhampatilart** [Upliner/CharMorph#4]
Python: Traceback (most recent call last):
  File "C:\Users\BMS\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\CharMorph\library.py", line 400, in execute
    morphing.create_charmorphs(obj)
  File "C:\Users\BMS\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\CharMorph\morphing.py", line 393, in create_charmorphs
    m.create_charmorphs_L2()
  File "C:\Users\BMS\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\CharMorph\morphing.py", line 324, in create_charmorphs_L2
    [prefixed_prop("prop_", self.morph_prop(k, v)) for k, v in self.morphs_l2.items()] +
  File "C:\Users\BMS\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\CharMorph\morphing.py", line 324, in <listcomp>
    [prefixed_prop("prop_", self.morph_prop(k, v)) for k, v in self.morphs_l2.items()] +
  File "C:\Users\BMS\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\CharMorph\morphing.py", line 55, in prefixed_prop
    return (prefix + prop[1]["name"], prop)
TypeError: '_PropertyDeferred' object is not subscriptable

location: <unknown location>:-1

<a href="https://ibb.co/CK7V0y2"><img src="https://i.ibb.co/CK7V0y2/Screenshot-2021-08-05-000113.jpg" alt="Screenshot-2021-08-05-000113" border="0"></a>

after Importing character 
cloth missing & get error like above

**Comment by shubhampatilart** [comment]
New update solved this
